<?php
session_start();
date_default_timezone_set('Asia/Kolkata');
$date= date("Y-m-d h:i:s"); 
ob_start();
include'config.php';
$id=$_GET['id'];
$admin1= $_SESSION['admin1'];
 $admin_name= $_SESSION['admin_name'];
 $adminid=$_SESSION["alid"];
 $sql_name = "select first_name FROM personal_details where  id='$id'";
$row=mysqli_query($sql_name);
$res=mysqli_fetch_array($row);
$first_name=$res['first_name'];
$sql = "DELETE FROM `personal_details` where  id='$id'";
mysqli_query($sql);
$sql1 = "DELETE FROM `children_detail` where  id='$id'";
mysqli_query($sql1);
$sql2 = "DELETE FROM `administrative_exp_detail` where  id='$id'";
mysqli_query($sql2);
$sql3 = "DELETE FROM `acadmic_detail` where  id='$id'";
mysqli_query($sql3);
$sql4 = "DELETE FROM `accomodation_detail` where  id='$id'";
mysqli_query($sql4);
$sql5 = "DELETE FROM `eligible` where  ulid='$id'";
mysqli_query($sql5);
$sql5 = "DELETE FROM `log_eligible_table` where  user_id='$id'";
mysqli_query($sql5);
$sql6 = "DELETE FROM `nonteaching_staff_exp` where  id='$id'";
mysqli_query($sql6);
$sql7 = "DELETE FROM `spouse_detail` where  id='$id'";
mysqli_query($sql7);
$sql8 = "DELETE FROM `teaching_experience_detail` where  id='$id'";
mysqli_query($sql8);
$sql9 = "DELETE FROM `refrence_detail` where  id='$id'";
mysqli_query($sql9);
$sql10 = "DELETE FROM `other_employee` where  id='$id'";
mysqli_query($sql10);
$log_sql="insert into log_eligible_table(admin_email,admin_id,user_name,user_id,comment,eligible_status,dt_created,name) values('$admin1','$adminid','$first_name','$id','9','','$date','$admin_name')";
 $row=mysqli_query($log_sql);
echo "succ";
?> 
